name: Aggiorna dati LIMET

permissions:
  contents: write

on:
  schedule:
    - cron: "0,10,20,30,40,50 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Aggiorna dati LIMET
        run: node aggiornaLimet.js

      - name: Commit e push dei nuovi dati
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "🔄 Aggiornamento automatico dati LIMET" || echo "Nessuna modifica da commitare"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main

      - name: Trigger nuovo deploy su Vercel
        run: curl -X POST "${{ secrets.VERCEL_HOOK }}"
